version: "3.1"

services:
  nginx:
    image: enrikerf/nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 9009:9009
    volumes:
      - ./app:/var/www/app
    environment:
      PUBLIC_FOLDER: /var/www/app/public
      APP_ENV: dev
  php-fpm:
    image: enrikerf/php-fpm-xdebug:latest
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app
    environment:
      PHP_IDE_CONFIG: serverName=docker.local
